name: Docker Image CI

env:
  TAG: '2.2.x'
  
on:
  push:
    branches: [ "2.2.x" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest
    name: Build image
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Build and push on grandnode2
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            GIT_COMMIT=${{ github.sha }}
            GIT_BRANCH=${{ github.ref_name }}
          push: true
          platforms: linux/amd64
          tags: grandnode/grandnode2:${{ env.TAG }}
      - name: Build and push on develop
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            GIT_COMMIT=${{ github.sha }}
            GIT_BRANCH=${{ github.ref_name }}
          push: true
          platforms: linux/amd64
          tags: grandnode/develop:${{ env.TAG }}
